C=======================================================================
C Abaqus Official Example: HETVAL for Heat Generation
C Define internal heat generation
C=======================================================================
      SUBROUTINE HETVAL(CMNAME,TEMP,TIME,DTIME,STATEV,FLUX,
     1 PREDEF,DPRED,COORMS,NOEL,NPT,LAYER,KSPT,KSTEP,KINC)
C
      INCLUDE 'ABA_PARAM.INC'
C
      CHARACTER*80 CMNAME
      DIMENSION FLUX(2), TIME(2), STATEV(*), PREDEF(*), DPRED(*),
     1 COORMS(3)
C
C     USER SUBROUTINE TO DEFINE HEAT GENERATION
C
C     FLUX(1) - HEAT GENERATION PER UNIT VOLUME (RPL)
C     FLUX(2) - DERIVATIVE OF RPL WITH RESPECT TO TEMPERATURE
C
C     EXAMPLE: HEAT GENERATION PROPORTIONAL TO PLASTIC WORK
C     RPL = ETA * SIGMA_Y * EPS_PLAS_DOT
C
      ETA = 0.9D0       ! TAYLOR-QUINNEY COEFFICIENT
C
C     GET EQUIVALENT PLASTIC STRAIN RATE FROM STATEV
C     ASSUME STATEV(1) = EQUIVALENT PLASTIC STRAIN
C     ASSUME STATEV(2) = EQUIVALENT PLASTIC STRAIN RATE
      EQPS_RATE = STATEV(2)
C
C     GET YIELD STRESS (SIMPLIFIED)
      SIGMA_Y = 200.D6   ! PA
C
C     CALCULATE HEAT GENERATION
      FLUX(1) = ETA * SIGMA_Y * EQPS_RATE
      FLUX(2) = 0.D0     ! DERIVATIVE WRT TEMP
C
      RETURN
      END
