C=======================================================================
C Abaqus Official Example: UMAT for Von Mises Plasticity
C Isotropic Hardening with Radial Return Algorithm
C=======================================================================
      SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     1 RPL,DDSDDT,DRPLDE,DRPLDT,
     2 STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,
     3 PREDEF,DPRED,CMNAME,NDI,NSHR,NTENS,NSTATV,
     4 PROPS,NPROPS,COORDS,DROT,PNEWDT,
     5 CELENT,DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,
     6 KSTEP,KINC)
C
      INCLUDE 'ABA_PARAM.INC'
C
      CHARACTER*80 CMNAME
      DIMENSION STRESS(NTENS),STATEV(NSTATV),
     1 DDSDDE(NTENS,NTENS),DDSDDT(NTENS),DRPLDE(NTENS),
     2 STRAN(NTENS),DSTRAN(NTENS),TIME(2),PREDEF(1),DPRED(1),
     3 COORDS(3),DROT(3,3),DFGRD0(3,3),DFGRD1(3,3)
C
      DIMENSION EELAS(6),EPLAS(6),FLOW(6)
      PARAMETER (ONE=1.0D0,TWO=2.0D0,THREE=3.0D0,SIX=6.0D0,
     1           ENUMAX=.4999D0,NEWTON=10,TOLER=1.0D-6)
C
C-----------------------------------------------------------------------
C     UMAT FOR ISOTROPIC ELASTIC-PLASTICITY WITH VON MISES YIELD
C     ISOTROPIC HARDENING - RADIAL RETURN ALGORITHM
C-----------------------------------------------------------------------
C     PROPS(1) - E
C     PROPS(2) - NU
C     PROPS(3) - SYIELD
C     PROPS(4) - HARD
C-----------------------------------------------------------------------
C
C     STATEV(1) - EQPLAS   (EQUIVALENT PLASTIC STRAIN)
C     STATEV(2) - DEQPLAS  (INCREMENT OF EQPLAS)
C-----------------------------------------------------------------------
C
C     ELASTIC PROPERTIES
      EMOD=PROPS(1)
      ENU=MIN(PROPS(2),ENUMAX)
      EBULK3=EMOD/(ONE-TWO*ENU)
      EG2=EMOD/(ONE+ENU)
      EG=EG2/TWO
      EG3=THREE*EG
      ELAM=(EBULK3-EG2)/THREE
C
C     ELASTIC STIFFNESS
C
      DO 20 K1=1,NDI
        DO 10 K2=1,NDI
          DDSDDE(K2,K1)=ELAM
 10     CONTINUE
        DDSDDE(K1,K1)=EG2+ELAM
 20   CONTINUE
      DO 40 K1=NDI+1,NTENS
        DDSDDE(K1,K1)=EG
 40   CONTINUE
C
C     CALCULATE STRESS FROM ELASTIC STRAINS
C
      DO 70 K1=1,NTENS
        DO 60 K2=1,NTENS
          STRESS(K2)=STRESS(K2)+DDSDDE(K2,K1)*DSTRAN(K1)
 60     CONTINUE
 70   CONTINUE
C
C     RECOVER ELASTIC AND PLASTIC STRAINS
C
      DO 80 K1=1,NTENS
        EELAS(K1)=STATEV(K1)
        EPLAS(K1)=STATEV(K1+NTENS)
 80   CONTINUE
      EQPLAS=STATEV(1+2*NTENS)
C
C     IF PLASTICITY IS PRESENT, DO THE RETURN MAPPING
C
      IF (NPROPS.GT.2) THEN
        SYIELD=PROPS(3)
        HARD=PROPS(4)
C
C       COMPUTE EQUIVALENT STRESS
        SMISES=(STRESS(1)-STRESS(2))*(STRESS(1)-STRESS(2))+
     1         (STRESS(2)-STRESS(3))*(STRESS(2)-STRESS(3))+
     1         (STRESS(3)-STRESS(1))*(STRESS(3)-STRESS(1))
        DO 90 K1=NDI+1,NTENS
          SMISES=SMISES+SIX*STRESS(K1)*STRESS(K1)
 90     CONTINUE
        SMISES=SQRT(SMISES/TWO)
C
C       CHECK YIELD CONDITION
        IF (SMISES.GT.(ONE+TOLER)*SYIELD) THEN
C
C         MATERIAL IS PLASTIC - DETERMINE FLOW DIRECTION
          SHYDRO=(STRESS(1)+STRESS(2)+STRESS(3))/THREE
          FLOW(1)=(STRESS(1)-SHYDRO)/SMISES
          FLOW(2)=(STRESS(2)-SHYDRO)/SMISES
          FLOW(3)=(STRESS(3)-SHYDRO)/SMISES
          DO 100 K1=NDI+1,NTENS
            FLOW(K1)=STRESS(K1)/SMISES
 100      CONTINUE
C
C         SOLVE FOR EQUIVALENT PLASTIC STRAIN INCREMENT USING NEWTON'S METHOD
          DEQPL=(SMISES-SYIELD)/(EG3+HARD)
          DO 120 KEWTON=1,NEWTON
            RHS=SMISES-EG3*DEQPL-SYIELD-HARD*DEQPL
            DEQPL=DEQPL+RHS/(EG3+HARD)
            IF (ABS(RHS).LT.TOLER*SYIELD) GOTO 130
 120      CONTINUE
          WRITE(*,*) 'WARNING: PLASTICITY LOOP DID NOT CONVERGE'
 130      CONTINUE
C
C         UPDATE STRESS
          DO 140 K1=1,NDI
            STRESS(K1)=FLOW(K1)*SYIELD+SHYDRO
 140      CONTINUE
          DO 150 K1=NDI+1,NTENS
            STRESS(K1)=FLOW(K1)*SYIELD
 150      CONTINUE
C
C         UPDATE ELASTIC AND PLASTIC STRAINS
          DO 160 K1=1,NDI
            EELAS(K1)=EELAS(K1)+DSTRAN(K1)-DEQPL*FLOW(K1)
            EPLAS(K1)=EPLAS(K1)+DEQPL*FLOW(K1)
 160      CONTINUE
          DO 170 K1=NDI+1,NTENS
            EELAS(K1)=EELAS(K1)+DSTRAN(K1)-DEQPL*FLOW(K1)*TWO
            EPLAS(K1)=EPLAS(K1)+DEQPL*FLOW(K1)*TWO
 170      CONTINUE
          EQPLAS=EQPLAS+DEQPL
C
C         COMPUTE CONSISTENT TANGENT MODULUS
          EFFG=EG*SYIELD/SMISES
          EFFG2=TWO*EFFG
          EFFG3=THREE*EFFG2/(TWO*EG3)
          EFFLAM=(EBULK3-EFFG2)/THREE
          DO 220 K1=1,NDI
            DO 210 K2=1,NDI
              DDSDDE(K2,K1)=EFFLAM
 210        CONTINUE
            DDSDDE(K1,K1)=EFFG2+EFFLAM
 220      CONTINUE
          DO 230 K1=NDI+1,NTENS
            DDSDDE(K1,K1)=EFFG
 230      CONTINUE
          DO 250 K1=1,NTENS
            DO 240 K2=1,NTENS
              DDSDDE(K2,K1)=DDSDDE(K2,K1)-EFFG3*FLOW(K2)*FLOW(K1)
 240        CONTINUE
 250      CONTINUE
        END IF
      END IF
C
C     STORE STRAINS IN STATE VARIABLE ARRAY
C
      DO 310 K1=1,NTENS
        STATEV(K1)=EELAS(K1)
        STATEV(K1+NTENS)=EPLAS(K1)
 310  CONTINUE
      STATEV(1+2*NTENS)=EQPLAS
C
      RETURN
      END
